import type { BlogPost } from "../types/blogPosts";

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "Transforming Design",
    category: "Design",
    excerpt: "Discover how we approach design with innovative solutions.",
    imageUrl: "/assets/images/design.jpg",
    link: "/blog/design",
    author: "John Doe",
    authorImage: "/assets/images/john-doe.jpg",
    date: "February 1, 2023",
    readTime: "2 min read",
  },
  {
    id: 2,
    title: "Planet Tech",
    category: "Tech",
    excerpt: "Exploring the latest in technology and digital trends.",
    imageUrl: "/assets/images/tech.jpg",
    link: "/blog/tech",
    author: "Jane Smith",
    authorImage: "/assets/images/jane-smith.jpg",
    date: "January 1, 2023",
    readTime: "3 min read",
  },
  {
    id: 3,
    title: "Business Solutions",
    category: "Business",
    excerpt: "Tailored solutions for modern business challenges.",
    imageUrl: "/assets/images/business.jpg",
    link: "/blog/business",
    author: "Bob Johnson",
    authorImage: "/assets/images/bob-johnson.jpg",
    date: "March 1, 2023",
    readTime: "4 min read",
  },
  {
    id: 4,
    title: "Creative Strategies",
    category: "Creative",
    excerpt: "Unleashing creativity to solve complex problems.",
    imageUrl: "/assets/images/creative.jpg",
    link: "/blog/creative",
    author: "Sarah Lee",
    authorImage: "/assets/images/sarah-lee.jpg",
    date: "April 1, 2023",
    readTime: "5 min read",
  },
  {
    id: 5,
    title: "Future of AI",
    category: "AI",
    excerpt: "Exploring the impact of AI on various industries.",
    imageUrl: "/assets/images/ai.jpg",
    link: "/blog/ai",
    author: "Michael Chen",
    authorImage: "/assets/images/michael-chen.jpg",
    date: "May 1, 2023",
    readTime: "6 min read",
  },
  {
    id: 6,
    title: "Sustainable Growth",
    category: "Sustainable",
    excerpt: "Strategies for achieving sustainable business growth.",
    imageUrl: "/assets/images/sustainable.jpg",
    link: "/blog/sustainable",
    author: "Emily Brown",
    authorImage: "/assets/images/emily-brown.jpg",
    date: "June 1, 2023",
    readTime: "7 min read",
  },
];
